use crate::calculator::Node;
use std::str::FromStr;

#[LALR] grammar;

pub L: Node = {
    <e:E> "n" => e,
}

E: Node = {
    <e:E> "+" <t:T> => e + t,
    <t:T> => t,
}

T: Node = {
    <t:T> "*" <f:F> => t * f,
    <f:F> => f,
}

F: Node = {
    "(" <e:E> ")" => e,
    <s:r"[0-9]+"> => {
        let lit = i32::from_str(s).unwrap();
        Node::lit(lit)
    },
    <s:r"[a-zA-Z]\w*"> => {
        Node::id(s.to_owned())
    }
}